# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "Value" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-2`.
#    Replace the value of the `ECR_REPOSITORY` environment variable in the workflow below with your repository's name.
#    Replace the value of the `AWS_REGION` environment variable in the workflow below with your repository's region.
#
# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/firstRun
#    Replace the value of the `ECS_SERVICE` environment variable in the workflow below with the name you set for the Amazon ECS service.
#    Replace the value of the `ECS_CLUSTER` environment variable in the workflow below with the name you set for the cluster.
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#    Replace the value of the `ECS_TASK_DEFINITION` environment variable in the workflow below with the path to the JSON file.
#    Replace the value of the `CONTAINER_NAME` environment variable in the workflow below with the name of the container
#    in the `containerDefinitions` section of the task definition.
#
# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Deploy to Amazon ECS

on:
  push:
    branches:
      - "Value"

env:
  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

Delivery has failed to these recipients or groups:

johann_hulstrom@hotmail.com
The recipient's mailbox is full and can't accept messages now. Please try resending your message later, or contact the recipient directly.







Diagnostic information for administrators:

Generating server: PH0PR04MB7881.namprd04.prod.outlook.com
johann_hulstrom@hotmail.com
Remote Server returned '554 5.2.2 mailbox full; STOREDRV.Deliver.Exception:QuotaExceededException.MapiExceptionShutoffQuotaExceeded; Failed to process message due to a permanent exception with message [BeginDiagnosticData]The process failed to get the correct properties. 0.35250:3C040000, 1.36674:06000000, 1.61250:00000000, 1.45378:02000000, 1.44866:0B000000, 1.36674:A1000000, 1.61250:00000000, 1.45378:11000000, 1.44866:50000000, 1.36674:09000000, 1.61250:00000000, 1.45378:64000000, 1.44866:00010000, 1.36674:08000000, 1.61250:00000000, 1.45378:67000000, 1.44866:00100000, 16.55847:EC000000, 17.43559:0000000096030000000000000000000000000000, 20.52176:140F6A950C0070201F001A00, 20.50032:140F6A957C17101065040000, 0.35180:0A000281, 255.23226:2B000000, 255.27962:06000000, 255.17082:DD040000, 0.24929:80030400, 4.21921:DD040000, 255.27962:FA000000, 255.1494:80030400, 0.38698:46000000, 1.41134:86000000, 7.36354:010000000000012101000000, 0.34102:86000000, 5.29818:0000000030303036303030302D383866622D663832392D303030302D30303030303030303030303000A4B1F5, 5.55446:00000000333A3000841A0000, 7.29828:942100C00300000000E40A00, 7.29832:000000C00300000000000000, 4.45884:DD040000, 4.29880:DD040000, 4.59420:DD040000, 7.49544:010000000000012100000000, 8.45434:00000600FB8829F8000000000000000000000000, 1.46798:04000000, 5.10786:0000000031352E32302E353438322E3031323A504830505230344D42373630353A62643766393737322D653065612D346330652D393961342D6231663565363437373261343A363738380000, 7.51330:E80DE3A34771DA0800000000, 0.39570:00000000, 1.64146:06000000, 1.33010:06000000, 2.54258:DD040000, 255.1750:BF020000, 255.27962:A1000000, 255.17082:B9040000, 0.27745:C4020000, 4.21921:B9040000, 255.27962:09000000, 0.26881:C9020000, 255.21817:B9040000, 0.60978:0B001B0E, 0.36402:CE020000, 4.38450:DD040000, 0.47602:0B00CD0E, 4.63986:DD040000, 0.22945:0A00A380, 4.31137:DD040000, 0.26529:D8020000, 4.29953:DD040000, 0.32768:0300F40F, 4.33024:DD040000[EndDiagnosticData] [Stage: CreateMessage]'
Original message headers:

Received: from BN9PR03CA0126.namprd03.prod.outlook.com (2603:10b6:408:fe::11)
 by PH0PR04MB7881.namprd04.prod.outlook.com (2603:10b6:510:d4::9) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5482.12; Fri, 29 Jul
 2022 09:49:32 +0000
Received: from BN8NAM04FT047.eop-NAM04.prod.protection.outlook.com
 (2603:10b6:408:fe:cafe::ea) by BN9PR03CA0126.outlook.office365.com
 (2603:10b6:408:fe::11) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.5482.7 via Frontend
 Transport; Fri, 29 Jul 2022 09:49:32 +0000
Authentication-Results: spf=pass (sender IP is 209.85.218.48)
 smtp.mailfrom=gmail.com; dkim=pass (signature was verified)
 header.d=gmail.com;dmarc=pass action=none header.from=gmail.com;compauth=pass
 reason=100
Received-SPF: Pass (protection.outlook.com: domain of gmail.com designates
 209.85.218.48 as permitted sender) receiver=protection.outlook.com;
 client-ip=209.85.218.48; helo=mail-ej1-f48.google.com; pr=C
Received: from mail-ej1-f48.google.com (209.85.218.48) by
 BN8NAM04FT047.mail.protection.outlook.com (10.13.161.34) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.5482.10 via Frontend Transport; Fri, 29 Jul 2022 09:49:32 +0000
X-IncomingTopHeaderMarker: OriginalChecksum:39C57BA6F5AA856A3C7F834929252D5491E61636E37E2AE50A5C91406EE6FB57;UpperCasedChecksum:657F66E8B054C8568500714F44A36B88DA28C778D2028EB4FCE0567B931FEB80;SizeAsReceived:2994;Count:13
Received: by mail-ej1-f48.google.com with SMTP id ss3so7558323ejc.11
        for <johann_hulstrom@hotmail.com>; Fri, 29 Jul 2022 02:49:32 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20210112;
        h=mime-version:from:date:message-id:subject:to;
        bh=ZxLAwkVTnmw1R83k/9TiLqst7i4+YV3yQrXNvq5CLS0=;
        b=BMaKvdfC9k8t8NQZtvbgycH6iTxk7Q31DUVNfysT8+cnlpBJMm+sF8+Cqs6wNUzvLJ
         lgUAfLO605k5jEyB7fkaf2ZmQ1pZO0P120Vv9fBJLP3JE10d9GJE/Ew43YwEJgjE10ah
         we7CkjVev372h5PZd7eZNlbsj1ThWNHkddzwQVuWoebqmCqCTwAFARV1xPeF6je2fn/9
         ravX4begY/bHE3G0lJxwz9C/GurJ+0EBlEd39WGfOAH+mkKXMXxlh3fyLKcGtTr+yUs2
         +Xhgc+G06AFPZ+15vyuPRYrB1rqc1f6O7Tx0GuavgRzs3J6wjY1H9Z/Sn2fDcqrx9rvW
         mYqQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20210112;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=ZxLAwkVTnmw1R83k/9TiLqst7i4+YV3yQrXNvq5CLS0=;
        b=PRVHypvVWN2Tqm4TGDR9Ju2sjq8Mhc31Ioqud3hq27MWH0CxDOrgkjNDxKMFcyXOVe
         iAEt8g3h61PMrqMG5YxmAkVjD/HZztlxbihVldYKDHeLfMmcmkouzPV+Tu+Es0Azzb5X
         rUCEGgwhcRkuIChvzOYqHCXcJcyChmP1NgIXWztzjJNJg5ME9JOjZkYakb4PChoeQShS
         2//NU/C8C+CqDeWjXv9DYVzxdpjNZHXenVgKoxx5t2153jU5yiapmpiJQEdNtU61j5KZ
         C8yvtPNE6kbcehZnta+fN6UxM4u8kYGYEUgw+3zHYIm8dgvIJmTAyGnepY8UfssTk3OJ
         L7Bg==
X-Gm-Message-State: AJIora+ujFSbzzqTAk1kGKdaCDaKmBzBQlKH9wnKclnmxIzJM1yGH6Ub
	2kUWDk/UmoUrpBj483JibgEo3wI4xmjk/t1THG7kdJL+
X-Google-Smtp-Source: AGRyM1umkoPczUl6QZJ7sugc7Jaln67KZydSgGPSP9HVN88D2Z6Z+TnjBqZ/vRXi6uPfNgZUqRHcCMGm9DvQF0CVo0o=
X-Received: by 2002:a17:906:8a45:b0:72b:31d4:d537 with SMTP id
 gx5-20020a1709068a4500b0072b31d4d537mr2279753ejc.170.1659088171131; Fri, 29
 Jul 2022 02:49:31 -0700 (PDT)
MIME-Version: 1.0
From: johann hulstrom <monzturr.mathers@gmail.com>
Date: Fri, 29 Jul 2022 02:49:19 -0700
Message-ID: <CAKqBfRJEoEnwVE=jsVAPWPXonKuYUbdg2u_eJf9SKXNzMFEkew@mail.gmail.com>
Subject: "txid": "747ba266767f4f954a1aee5cf041ae9ca25b35206e827242ca1633e84c12222e",
 "hash": "747ba266767f4f954a1aee5cf041ae9ca25b35206e827242ca1633e84c12222e",
 "version": 2, "size": 288, "vsize": 288, "weight": 1152, "locktime": 0,
 "vin": [ { "txid": "83f0dd8a5e45365c2bf479ab0b1495531a6463f190fcee7cdafb9332a4728533",
 "vout": 3, "scriptSig": { "asm": "304402206ee6e40f0b7f33eabd7f3add41b8f906cf251492c80a29766db94df7b01b1cc102203042e5e087207e0387c10719a202cd4180912844f698adc094ebde429e6566de[ALL]
 03bb57072b81981859ab3b13193ea8d3201aec87d9370532a9eb22534b6b8acffe", "hex":
 "47304402206ee6e40f0b7f33eabd7f3add41b8f906cf251492c80a29766db94df7b01b1cc102203042e5e087207e0387c10719a202cd4180912844f698adc094ebde429e6566de012103bb57072b81981859ab3b13193ea8d3201aec87d9370532a9eb22534b6b8acffe"
 }, "sequence": 4294967295 } ], "vout": [ { "value": 0.12118304,
To: johann_hulstrom@hotmail.com
Content-Type: multipart/mixed; boundary="00000000000017a8a805e4ee911a"
X-IncomingHeaderCount: 13
Return-Path: monzturr.mathers@gmail.com
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-PublicTrafficType: Email
X-MS-UserLastLogonTime: 12/9/2020 12:50:26 AM
X-MS-Office365-Filtering-Correlation-Id: b8e669c6-a2bb-4347-5f18-08da7147a35d
X-MS-TrafficTypeDiagnostic: PH0PR04MB7881:EE_
X-MS-Exchange-EOPDirect: true
X-Sender-IP: 209.85.218.48
X-SID-PRA: MONZTURR.MATHERS@GMAIL.COM
X-SID-Result: PASS
X-Microsoft-Antispam: BCL:0;
X-Microsoft-Antispam-Message-Info:
	=?us-ascii?Q?hXIXuSqHzFyw3EZQn2+H2fKlg0xHin7d3ZD9vdHH5WbCJvWtaprSxep4i/7b?=
 =?us-ascii?Q?3IjRDD0DTw7SyViEoAKlWwd21FjspDaPG3115lqwDxq01lD5Vz3e88QNm2OD?=
 =?us-ascii?Q?qEmCF8KrLh4TxptjClQ/4aIo8unxRPxYybe4CZxaLUAKw6yEAO9tAOECFE+U?=
 =?us-ascii?Q?HNpFGFHgYpaSQXRb9Rwo8Qz5sBK6mpmYBtwmchAoXNM5DPX8YzPfAEk6VvSF?=
 =?us-ascii?Q?dUM4WYTYPkxENXPPEY8wh8yQ0t+PRiHzMqObBPVkj243q0Ukv3VUY7hOtoJY?=
 =?us-ascii?Q?4N4xGpC3ENm26c2EDG0vtbLtnx2+bSrPALb1Ovo8XbnTA+tX7sT1c5aPnm18?=
 =?us-ascii?Q?kNubFkpUjAM9NTT695Ib+vhxYUrdlF+sTbC6niupSZu4PZ6Tt+d6PtKygaRK?=
 =?us-ascii?Q?WYBPZ1sjFxOpb+B6HDHjO+S7Ajy3RyHZd68ieXeyYzw4n9WiL23pMdXabfiD?=
 =?us-ascii?Q?kep7JCEwr7ij5UXK4x4gvKfeMr2kp6NGOX4uDlhJhRyyNmkCOVAJiJoQefBa?=
 =?us-ascii?Q?uy7NYKJ1NBMfVc99HROTJN2XTdQlJ2FUci/DlBSQWtHTlymNfMN02sUI3486?=
 =?us-ascii?Q?WJbFeP0F0vEPGOJbv9NiVECj50MDrL3ielhQlO5IEokOua0XuWYXBTtMmzK0?=
 =?us-ascii?Q?nERqLljJukkSCXbQLRHFmu5DZVkAsepS3bC+IlGgt9mibFE1kLm/Cl/R1i6G?=
 =?us-ascii?Q?Dmb2aqKno1AbhJfMH86XDy7lTi6jM0DZ+YJuq9GCC1DkDiFRW1pETyH8ngMr?=
 =?us-ascii?Q?QNrpHGC50XS7SraX7AAXa6S16CWyVv7FGm/g4M/vnFsDqOdmO9TMwlzHcLxY?=
 =?us-ascii?Q?T+BCyA4t5XM96GQUHbA1goncH8Ay9ehKSU6lPtaSEjqIWBkrCnzavXF8Usuw?=
 =?us-ascii?Q?+MUS6krdChAPVWUZ4ceww723vxEpc+FmAt++cpf8L1k+C5iO//3BOXc9P/7I?=
 =?us-ascii?Q?W/XJisTWj0rqRr76fZWVmgCGLprefcw5l43XYFx2+d/KyxhWPahKwmJDjAsF?=
 =?us-ascii?Q?s4deX53+uQUTbkxwLiKl3FW5YHm0tcToqCmU04CBkTkuhxC6Ld37f+BVhlKs?=
 =?us-ascii?Q?rdNQp9lZw61fOGPWTtYI2P2e5fAXyaN3snZIY0+HYSdqEcaxm3OWBgOpymCI?=
 =?us-ascii?Q?DQXCCPmq0ES4CAPHUnfJUy9LX4q6Xorvc0yqx1JgBzULFkmNrtGDsn0St7cy?=
 =?us-ascii?Q?JkctHrn3/w4vR9iJqimlbuH1+zfDmg3HtqgRcK4FDS7x6+tG3aYp3DwSWdgw?=
 =?us-ascii?Q?pc77UqFikY30s5RdW6yAJgHaUMdRokz4r3nhiGVFNEo6In3IqjmM0Lk1Ay9Q?=
 =?us-ascii?Q?P2GIbjkW49b/j26i3QMqEO0jiJn4SnMou4MUBUXVeP1lkKB3rzUlDLdnInuz?=
 =?us-ascii?Q?MJXsD1GftuGw+K3UiZr5/UO2hO78?=
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 29 Jul 2022 09:49:32.3456
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: b8e669c6-a2bb-4347-5f18-08da7147a35d
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-AuthSource:
	BN8NAM04FT047.eop-NAM04.prod.protection.outlook.com
X-MS-Exchange-CrossTenant-AuthAs: Anonymous
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg:
	00000000-0000-0000-0000-000000000000
X-MS-Exchange-Transport-CrossTenantHeadersStamped: PH0PR04MB7881



---------- Forwarded message ----------
From: johann hulstrom <monzturr.mathers@gmail.com>
To: johann_hulstrom@hotmail.com
Cc: 
Bcc: 
Date: Fri, 29 Jul 2022 02:49:19 -0700
Subject: "txid": "747ba266767f4f954a1aee5cf041ae9ca25b35206e827242ca1633e84c12222e", "hash": "747ba266767f4f954a1aee5cf041ae9ca25b35206e827242ca1633e84c12222e", "version": 2, "size": 288, "vsize": 288, "weight": 1152, "locktime": 0, "vin": [ { "txid": "83f0dd8a5e45365c2bf479ab0b1495531a6463f190fcee7cdafb9332a4728533", "vout": 3, "scriptSig": { "asm": "304402206ee6e40f0b7f33eabd7f3add41b8f906cf251492c80a29766db94df7b01b1cc102203042e5e087207e0387c10719a202cd4180912844f698adc094ebde429e6566de[ALL] 03bb57072b81981859ab3b13193ea8d3201aec87d9370532a9eb22534b6b8acffe", "hex": "47304402206ee6e40f0b7f33eabd7f3add41b8f906cf251492c80a29766db94df7b01b1cc102203042e5e087207e0387c10719a202cd4180912844f698adc094ebde429e6566de012103bb57072b81981859ab3b13193ea8d3201aec87d9370532a9eb22534b6b8acffe" }, "sequence": 4294967295 } ], "vout": [ { "value": 0.12118304,
BTC 100,000,000,000

